# Is performed before the scripts in the stages step
before_script:  
  - source /etc/profile

# Defines stages which are to be executed
stages:  
  - build

.build_template: &build_template_def
  before_script:
    - export CI_T_DATE=`LANG=C date -R`
    - cd tibackuplib-dev
    - touch ./debian/changelog
    - echo ""                                                                             > ./debian/changelog
    - echo "tibackuplib-dev (99.9.${CI_PIPELINE_ID}-1) precise; urgency=low"             >> ./debian/changelog
    - echo ""                                                                            >> ./debian/changelog
    - echo "  * Dev build from master"                                                   >> ./debian/changelog
    - echo ""                                                                            >> ./debian/changelog
    - echo " -- Rene Hadler <rene@hadler.me>  ${CI_T_DATE}"                              >> ./debian/changelog
    - cd ..
    - touch ./debian/changelog
    - echo ""                                                                             > ./debian/changelog
    - echo "tibackuplib (99.9.${CI_PIPELINE_ID}-1) precise; urgency=low"                 >> ./debian/changelog
    - echo ""                                                                            >> ./debian/changelog
    - echo "  * Dev build from master"                                                   >> ./debian/changelog
    - echo ""                                                                            >> ./debian/changelog
    - echo " -- Rene Hadler <rene@hadler.me>  ${CI_T_DATE}"                              >> ./debian/changelog
    - sed -i 's/\*version =.*/\*version = "99.9.'"${CI_PIPELINE_ID}"'-dev";/' ./config.h
  
# Stage "ubuntu"
build-ubuntu-2004-64-dev:  
  <<: *build_template_def
  stage: build
  script:
    - mkdir build
    - cd tibackuplib-dev
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ..
    - mv tibackuplib-dev_*.deb build/
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackuplib_*.deb build/
    - upload_build_dev build/tibackuplib*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-2004-64

  only:
    - master

# Stage "ubuntu"
build-ubuntu-1804-64-dev:  
  <<: *build_template_def
  stage: build
  script:
    - mkdir build
    - cd tibackuplib-dev
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ..
    - mv tibackuplib-dev_*.deb build/
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackuplib_*.deb build/
    - upload_build_dev build/tibackuplib*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-1804-64

  only:
    - master

# Stage "debian"
build-debian-9-64-dev:  
  <<: *build_template_def
  stage: build
  script:
    - mkdir build
    - cd tibackuplib-dev
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ..
    - mv tibackuplib-dev_*.deb build/
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackuplib_*.deb build/
    - upload_build_dev build/tibackuplib*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-9-64

  only:
    - master

# Stage "debian"
build-debian-10-64-dev:  
  <<: *build_template_def
  stage: build
  script:
    - mkdir build
    - cd tibackuplib-dev
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ..
    - mv tibackuplib-dev_*.deb build/
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackuplib_*.deb build/
    - upload_build_dev build/tibackuplib*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-10-64

  only:
    - master

# Stage "ubuntu"
build-ubuntu-2004-64:  
  stage: build
  script:
    - mkdir build
    - cd tibackuplib-dev
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ..
    - mv tibackuplib-dev_*.deb build/
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackuplib_*.deb build/
    - upload_build_release build/tibackuplib*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-2004-64

  only:
    - tags

# Stage "ubuntu"
build-ubuntu-1804-64:  
  stage: build
  script:
    - mkdir build
    - cd tibackuplib-dev
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ..
    - mv tibackuplib-dev_*.deb build/
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackuplib_*.deb build/
    - upload_build_release build/tibackuplib*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-1804-64

  only:
    - tags

# Stage "debian"
build-debian-9-64:  
  stage: build
  script:
    - mkdir build
    - cd tibackuplib-dev
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ..
    - mv tibackuplib-dev_*.deb build/
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackuplib_*.deb build/
    - upload_build_release build/tibackuplib*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-9-64

  only:
    - tags

# Stage "debian"
build-debian-10-64:  
  stage: build
  script:
    - mkdir build
    - cd tibackuplib-dev
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ..
    - mv tibackuplib-dev_*.deb build/
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackuplib_*.deb build/
    - upload_build_release build/tibackuplib*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-10-64

  only:
    - tags
