#ifndef TIBACKUPLIB_GLOBAL_H
#define TIBACKUPLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TIBACKUPLIB_LIBRARY)
#  define TIBACKUPLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TIBACKUPLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TIBACKUPLIB_GLOBAL_H
